using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QMS.Core.Models;

public class PhysicalCheckAndVisualInspectionViewModel
{
    public int Id { get; set; }
    public string? Report_No { get; set; }
    public string? Project_Name { get; set; }

    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
    public DateTime? Report_Date { get; set; }
    public string? Product_Cat_Ref { get; set; }
    public string? Product_Description { get; set; }
    public string? Batch_Code { get; set; }
    public string? PKD { get; set; }
    public int? Quantity { get; set; }
    public string? WiproBranding_Sample1 { get; set; }
    public string? WiproBranding_Sample2 { get; set; }
    public string? WiproBranding_Sample3 { get; set; }
    public string? WiproBranding_Sample4 { get; set; }
    public string? WiproBranding_Sample5 { get; set; }
    public string? WiproBranding_Result { get; set; }
    public string? ProductDriverLabels_Sample1 { get; set; }
    public string? ProductDriverLabels_Sample2 { get; set; }
    public string? ProductDriverLabels_Sample3 { get; set; }
    public string? ProductDriverLabels_Sample4 { get; set; }
    public string? ProductDriverLabels_Sample5 { get; set; }
    public string? ProductDriverLabels_Result { get; set; }
    public string? PackingStickers_Sample1 { get; set; }
    public string? PackingStickers_Sample2 { get; set; }
    public string? PackingStickers_Sample3 { get; set; }
    public string? PackingStickers_Sample4 { get; set; }
    public string? PackingStickers_Sample5 { get; set; }
    public string? PackingStickers_Result { get; set; }
    public string? Dimensions_Sample1 { get; set; }
    public string? Dimensions_Sample2 { get; set; }
    public string? Dimensions_Sample3 { get; set; }
    public string? Dimensions_Sample4 { get; set; }
    public string? Dimensions_Sample5 { get; set; }
    public string? Dimensions_Result { get; set; }
    public string? SurfaceFinish_Sample1 { get; set; }
    public string? SurfaceFinish_Sample2 { get; set; }
    public string? SurfaceFinish_Sample3 { get; set; }
    public string? SurfaceFinish_Sample4 { get; set; }
    public string? SurfaceFinish_Sample5 { get; set; }
    public string? SurfaceFinish_Result { get; set; }
    public string? SurfaceFinishLED_Sample1 { get; set; }
    public string? SurfaceFinishLED_Sample2 { get; set; }
    public string? SurfaceFinishLED_Sample3 { get; set; }
    public string? SurfaceFinishLED_Sample4 { get; set; }
    public string? SurfaceFinishLED_Sample5 { get; set; }
    public string? SurfaceFinishLED_Result { get; set; }
    public string? DFT_Sample1 { get; set; }
    public string? DFT_Sample2 { get; set; }
    public string? DFT_Sample3 { get; set; }
    public string? DFT_Sample4 { get; set; }
    public string? DFT_Sample5 { get; set; }
    public string? DFT_Result { get; set; }
    public string? Visual_Sample1 { get; set; }
    public string? Visual_Sample2 { get; set; }
    public string? Visual_Sample3 { get; set; }
    public string? Visual_Sample4 { get; set; }
    public string? Visual_Sample5 { get; set; }
    public string? Visual_Result { get; set; }
    public string? VisualLitUp_Sample1 { get; set; }
    public string? VisualLitUp_Sample2 { get; set; }
    public string? VisualLitUp_Sample3 { get; set; }
    public string? VisualLitUp_Sample4 { get; set; }
    public string? VisualLitUp_Sample5 { get; set; }
    public string? VisualLitUp_Result { get; set; }
    public string? PcbCobFitment_Sample1 { get; set; }
    public string? PcbCobFitment_Sample2 { get; set; }
    public string? PcbCobFitment_Sample3 { get; set; }
    public string? PcbCobFitment_Sample4 { get; set; }
    public string? PcbCobFitment_Sample5 { get; set; }
    public string? PcbCobFitment_Result { get; set; }
    public string? PcbCobFitmentNoGaps_Sample1 { get; set; }
    public string? PcbCobFitmentNoGaps_Sample2 { get; set; }
    public string? PcbCobFitmentNoGaps_Sample3 { get; set; }
    public string? PcbCobFitmentNoGaps_Sample4 { get; set; }
    public string? PcbCobFitmentNoGaps_Sample5 { get; set; }
    public string? PcbCobFitmentNoGaps_Result { get; set; }
    public string? PcbCobFitmentScrew_Sample1 { get; set; }
    public string? PcbCobFitmentScrew_Sample2 { get; set; }
    public string? PcbCobFitmentScrew_Sample3 { get; set; }
    public string? PcbCobFitmentScrew_Sample4 { get; set; }
    public string? PcbCobFitmentScrew_Sample5 { get; set; }
    public string? PcbCobFitmentScrew_Result { get; set; }
    public string? PcbCobFitmentWasher_Sample1 { get; set; }
    public string? PcbCobFitmentWasher_Sample2 { get; set; }
    public string? PcbCobFitmentWasher_Sample3 { get; set; }
    public string? PcbCobFitmentWasher_Sample4 { get; set; }
    public string? PcbCobFitmentWasher_Sample5 { get; set; }
    public string? PcbCobFitmentWasher_Result { get; set; }
    public string? PcbCobFitmentDrawing_Sample1 { get; set; }
    public string? PcbCobFitmentDrawing_Sample2 { get; set; }
    public string? PcbCobFitmentDrawing_Sample3 { get; set; }
    public string? PcbCobFitmentDrawing_Sample4 { get; set; }
    public string? PcbCobFitmentDrawing_Sample5 { get; set; }
    public string? PcbCobFitmentDrawing_Result { get; set; }
    public string? Soldering_Sample1 { get; set; }
    public string? Soldering_Sample2 { get; set; }
    public string? Soldering_Sample3 { get; set; }
    public string? Soldering_Sample4 { get; set; }
    public string? Soldering_Sample5 { get; set; }
    public string? Soldering_Result { get; set; }
    public string? SolderingSpatter_Sample1 { get; set; }
    public string? SolderingSpatter_Sample2 { get; set; }
    public string? SolderingSpatter_Sample3 { get; set; }
    public string? SolderingSpatter_Sample4 { get; set; }
    public string? SolderingSpatter_Sample5 { get; set; }
    public string? SolderingSpatter_Result { get; set; }
    public string? SolderingGlobule_Sample1 { get; set; }
    public string? SolderingGlobule_Sample2 { get; set; }
    public string? SolderingGlobule_Sample3 { get; set; }
    public string? SolderingGlobule_Sample4 { get; set; }
    public string? SolderingGlobule_Sample5 { get; set; }
    public string? SolderingGlobule_Result { get; set; }
    public string? WiringDressing_Sample1 { get; set; }
    public string? WiringDressing_Sample2 { get; set; }
    public string? WiringDressing_Sample3 { get; set; }
    public string? WiringDressing_Sample4 { get; set; }
    public string? WiringDressing_Sample5 { get; set; }
    public string? WiringDressing_Result { get; set; }
    public string? MechanicalFitment_Sample1 { get; set; }
    public string? MechanicalFitment_Sample2 { get; set; }
    public string? MechanicalFitment_Sample3 { get; set; }
    public string? MechanicalFitment_Sample4 { get; set; }
    public string? MechanicalFitment_Sample5 { get; set; }
    public string? MechanicalFitment_Result { get; set; }
    public string? LedLensGap_Sample1 { get; set; }
    public string? LedLensGap_Sample2 { get; set; }
    public string? LedLensGap_Sample3 { get; set; }
    public string? LedLensGap_Sample4 { get; set; }
    public string? LedLensGap_Sample5 { get; set; }
    public string? LedLensGap_Result { get; set; }
    public string? Gasket_Sample1 { get; set; }
    public string? Gasket_Sample2 { get; set; }
    public string? Gasket_Sample3 { get; set; }
    public string? Gasket_Sample4 { get; set; }
    public string? Gasket_Sample5 { get; set; }
    public string? Gasket_Result { get; set; }
    public string? GlassFragmentation_Sample1 { get; set; }
    public string? GlassFragmentation_Sample2 { get; set; }
    public string? GlassFragmentation_Sample3 { get; set; }
    public string? GlassFragmentation_Sample4 { get; set; }
    public string? GlassFragmentation_Sample5 { get; set; }
    public string? GlassFragmentation_Result { get; set; }
    public bool Deleted { get; set; }
    public int AddedBy { get; set; }
    public string? User { get; set; }
    public DateTime AddedOn { get; set; }
    public int? UpdatedBy { get; set; }
    public DateTime? UpdatedOn { get; set; }
    public string? Final_Result { get; set; }
    public string? TestedBy { get; set; }
    public string? VerifiedBy { get; set; }
}
