namespace QMS.Core.Models;

public class TemperatureRiseTestViewModel
{
    public int Id { get; set; }
    public string? ReportNo { get; set; }
    public DateTime? ReportDate { get; set; }
    public string? TestingLocation { get; set; }
    public string? ProductCatRef { get; set; }
    public string? ProductDescription { get; set; }
    public string? BatchCode { get; set; }
    public string? PKD { get; set; }
    public string? HeatSinkMaterial { get; set; }
    public string? HeatSinkWeight { get; set; }
    public string? LensDetails { get; set; }
    public string? ThermalPasteDetails { get; set; }
    public decimal? NominalOperatingVoltage { get; set; }
    public string? DriverUsed { get; set; }
    public int? NoOfDrivers { get; set; }
    public decimal? DriverOutputVoltage { get; set; }
    public decimal? DriverOutputCurrent { get; set; }
    public decimal? DriverAllowableTc { get; set; }
    public decimal? DriverAllowableTa { get; set; }
    public string? PcbMaterialMake { get; set; }
    public string? PcbSizeQty { get; set; }
    public string? LedUsed { get; set; }
    public int? NoOfLeds { get; set; }
    public int? NoOfLedsInSeries { get; set; }
    public int? NoOfLedsInParallel { get; set; }
    public decimal? LedRjTH { get; set; }
    public decimal? LedVf { get; set; }
    public decimal? LedIf { get; set; }
    public decimal? LedWdc { get; set; }
    public string? ProbeT1_Desc { get; set; }
    public string? ProbeT2_Desc { get; set; }
    public string? ProbeT3_Desc { get; set; }
    public string? ProbeT4_Desc { get; set; }
    public string? ProbeT5_Desc { get; set; }
    public string? ProbeT6_Desc { get; set; }
    public string? ProbeT7_Desc { get; set; }
    public string? ProbeT8_Desc { get; set; }
    public string? ProbeT9_Desc { get; set; }
    public string? ProbeT10_Desc { get; set; }
    public string? ProbeT11_Desc { get; set; }
    public string? ProbeT12_Desc { get; set; }
    public string? ProbeT13_Desc { get; set; }
    public string? ProbeT14_Desc { get; set; }
    public string? ProbeT15_Desc { get; set; }
    public string? ProbeT16_Desc { get; set; }
    public decimal? R1_TimeHrs { get; set; }
    public decimal? R1_T1 { get; set; }
    public decimal? R1_T2 { get; set; }
    public decimal? R1_T3 { get; set; }
    public decimal? R1_T4 { get; set; }
    public decimal? R1_T5 { get; set; }
    public decimal? R1_T6 { get; set; }
    public decimal? R1_T7 { get; set; }
    public decimal? R1_T8 { get; set; }
    public decimal? R1_T9 { get; set; }
    public decimal? R1_T10 { get; set; }
    public decimal? R1_T11 { get; set; }
    public decimal? R1_T12 { get; set; }
    public decimal? R1_T13 { get; set; }
    public decimal? R1_T14 { get; set; }
    public decimal? R1_T15 { get; set; }
    public decimal? R1_T16 { get; set; }
    public decimal? R1_VIN { get; set; }
    public decimal? R1_IIN { get; set; }
    public decimal? R1_PIN { get; set; }
    public decimal? R1_TJ { get; set; }
    public decimal? R2_TimeHrs { get; set; }
    public decimal? R2_T1 { get; set; }
    public decimal? R2_T2 { get; set; }
    public decimal? R2_T3 { get; set; }
    public decimal? R2_T4 { get; set; }
    public decimal? R2_T5 { get; set; }
    public decimal? R2_T6 { get; set; }
    public decimal? R2_T7 { get; set; }
    public decimal? R2_T8 { get; set; }
    public decimal? R2_T9 { get; set; }
    public decimal? R2_T10 { get; set; }
    public decimal? R2_T11 { get; set; }
    public decimal? R2_T12 { get; set; }
    public decimal? R2_T13 { get; set; }
    public decimal? R2_T14 { get; set; }
    public decimal? R2_T15 { get; set; }
    public decimal? R2_T16 { get; set; }
    public decimal? R2_VIN { get; set; }
    public decimal? R2_IIN { get; set; }
    public decimal? R2_PIN { get; set; }
    public decimal? R2_TJ { get; set; }
    public decimal? R3_TimeHrs { get; set; }
    public decimal? R3_T1 { get; set; }
    public decimal? R3_T2 { get; set; }
    public decimal? R3_T3 { get; set; }
    public decimal? R3_T4 { get; set; }
    public decimal? R3_T5 { get; set; }
    public decimal? R3_T6 { get; set; }
    public decimal? R3_T7 { get; set; }
    public decimal? R3_T8 { get; set; }
    public decimal? R3_T9 { get; set; }
    public decimal? R3_T10 { get; set; }
    public decimal? R3_T11 { get; set; }
    public decimal? R3_T12 { get; set; }
    public decimal? R3_T13 { get; set; }
    public decimal? R3_T14 { get; set; }
    public decimal? R3_T15 { get; set; }
    public decimal? R3_T16 { get; set; }
    public decimal? R3_VIN { get; set; }
    public decimal? R3_IIN { get; set; }
    public decimal? R3_PIN { get; set; }
    public decimal? R3_TJ { get; set; }
    public decimal? R4_TimeHrs { get; set; }
    public decimal? R4_T1 { get; set; }
    public decimal? R4_T2 { get; set; }
    public decimal? R4_T3 { get; set; }
    public decimal? R4_T4 { get; set; }
    public decimal? R4_T5 { get; set; }
    public decimal? R4_T6 { get; set; }
    public decimal? R4_T7 { get; set; }
    public decimal? R4_T8 { get; set; }
    public decimal? R4_T9 { get; set; }
    public decimal? R4_T10 { get; set; }
    public decimal? R4_T11 { get; set; }
    public decimal? R4_T12 { get; set; }
    public decimal? R4_T13 { get; set; }
    public decimal? R4_T14 { get; set; }
    public decimal? R4_T15 { get; set; }
    public decimal? R4_T16 { get; set; }
    public decimal? R4_VIN { get; set; }
    public decimal? R4_IIN { get; set; }
    public decimal? R4_PIN { get; set; }
    public decimal? R4_TJ { get; set; }
    public decimal? R5_TimeHrs { get; set; }
    public decimal? R5_T1 { get; set; }
    public decimal? R5_T2 { get; set; }
    public decimal? R5_T3 { get; set; }
    public decimal? R5_T4 { get; set; }
    public decimal? R5_T5 { get; set; }
    public decimal? R5_T6 { get; set; }
    public decimal? R5_T7 { get; set; }
    public decimal? R5_T8 { get; set; }
    public decimal? R5_T9 { get; set; }
    public decimal? R5_T10 { get; set; }
    public decimal? R5_T11 { get; set; }
    public decimal? R5_T12 { get; set; }
    public decimal? R5_T13 { get; set; }
    public decimal? R5_T14 { get; set; }
    public decimal? R5_T15 { get; set; }
    public decimal? R5_T16 { get; set; }
    public decimal? R5_VIN { get; set; }
    public decimal? R5_IIN { get; set; }
    public decimal? R5_PIN { get; set; }
    public decimal? R5_TJ { get; set; }
    public decimal? R6_TimeHrs { get; set; }
    public decimal? R6_T1 { get; set; }
    public decimal? R6_T2 { get; set; }
    public decimal? R6_T3 { get; set; }
    public decimal? R6_T4 { get; set; }
    public decimal? R6_T5 { get; set; }
    public decimal? R6_T6 { get; set; }
    public decimal? R6_T7 { get; set; }
    public decimal? R6_T8 { get; set; }
    public decimal? R6_T9 { get; set; }
    public decimal? R6_T10 { get; set; }
    public decimal? R6_T11 { get; set; }
    public decimal? R6_T12 { get; set; }
    public decimal? R6_T13 { get; set; }
    public decimal? R6_T14 { get; set; }
    public decimal? R6_T15 { get; set; }
    public decimal? R6_T16 { get; set; }
    public decimal? R6_VIN { get; set; }
    public decimal? R6_IIN { get; set; }
    public decimal? R6_PIN { get; set; }
    public decimal? R6_TJ { get; set; }
    public decimal? R7_TimeHrs { get; set; }
    public decimal? R7_T1 { get; set; }
    public decimal? R7_T2 { get; set; }
    public decimal? R7_T3 { get; set; }
    public decimal? R7_T4 { get; set; }
    public decimal? R7_T5 { get; set; }
    public decimal? R7_T6 { get; set; }
    public decimal? R7_T7 { get; set; }
    public decimal? R7_T8 { get; set; }
    public decimal? R7_T9 { get; set; }
    public decimal? R7_T10 { get; set; }
    public decimal? R7_T11 { get; set; }
    public decimal? R7_T12 { get; set; }
    public decimal? R7_T13 { get; set; }
    public decimal? R7_T14 { get; set; }
    public decimal? R7_T15 { get; set; }
    public decimal? R7_T16 { get; set; }
    public decimal? R7_VIN { get; set; }
    public decimal? R7_IIN { get; set; }
    public decimal? R7_PIN { get; set; }
    public decimal? R7_TJ { get; set; }
    public decimal? R8_TimeHrs { get; set; }
    public decimal? R8_T1 { get; set; }
    public decimal? R8_T2 { get; set; }
    public decimal? R8_T3 { get; set; }
    public decimal? R8_T4 { get; set; }
    public decimal? R8_T5 { get; set; }
    public decimal? R8_T6 { get; set; }
    public decimal? R8_T7 { get; set; }
    public decimal? R8_T8 { get; set; }
    public decimal? R8_T9 { get; set; }
    public decimal? R8_T10 { get; set; }
    public decimal? R8_T11 { get; set; }
    public decimal? R8_T12 { get; set; }
    public decimal? R8_T13 { get; set; }
    public decimal? R8_T14 { get; set; }
    public decimal? R8_T15 { get; set; }
    public decimal? R8_T16 { get; set; }
    public decimal? R8_VIN { get; set; }
    public decimal? R8_IIN { get; set; }
    public decimal? R8_PIN { get; set; }
    public decimal? R8_TJ { get; set; }
    public decimal? R9_TimeHrs { get; set; }
    public decimal? R9_T1 { get; set; }
    public decimal? R9_T2 { get; set; }
    public decimal? R9_T3 { get; set; }
    public decimal? R9_T4 { get; set; }
    public decimal? R9_T5 { get; set; }
    public decimal? R9_T6 { get; set; }
    public decimal? R9_T7 { get; set; }
    public decimal? R9_T8 { get; set; }
    public decimal? R9_T9 { get; set; }
    public decimal? R9_T10 { get; set; }
    public decimal? R9_T11 { get; set; }
    public decimal? R9_T12 { get; set; }
    public decimal? R9_T13 { get; set; }
    public decimal? R9_T14 { get; set; }
    public decimal? R9_T15 { get; set; }
    public decimal? R9_T16 { get; set; }
    public decimal? R9_VIN { get; set; }
    public decimal? R9_IIN { get; set; }
    public decimal? R9_PIN { get; set; }
    public decimal? R9_TJ { get; set; }
    public decimal? R10_TimeHrs { get; set; }
    public decimal? R10_T1 { get; set; }
    public decimal? R10_T2 { get; set; }
    public decimal? R10_T3 { get; set; }
    public decimal? R10_T4 { get; set; }
    public decimal? R10_T5 { get; set; }
    public decimal? R10_T6 { get; set; }
    public decimal? R10_T7 { get; set; }
    public decimal? R10_T8 { get; set; }
    public decimal? R10_T9 { get; set; }
    public decimal? R10_T10 { get; set; }
    public decimal? R10_T11 { get; set; }
    public decimal? R10_T12 { get; set; }
    public decimal? R10_T13 { get; set; }
    public decimal? R10_T14 { get; set; }
    public decimal? R10_T15 { get; set; }
    public decimal? R10_T16 { get; set; }
    public decimal? R10_VIN { get; set; }
    public decimal? R10_IIN { get; set; }
    public decimal? R10_PIN { get; set; }
    public decimal? R10_TJ { get; set; }
    public decimal? R11_TimeHrs { get; set; }
    public decimal? R11_T1 { get; set; }
    public decimal? R11_T2 { get; set; }
    public decimal? R11_T3 { get; set; }
    public decimal? R11_T4 { get; set; }
    public decimal? R11_T5 { get; set; }
    public decimal? R11_T6 { get; set; }
    public decimal? R11_T7 { get; set; }
    public decimal? R11_T8 { get; set; }
    public decimal? R11_T9 { get; set; }
    public decimal? R11_T10 { get; set; }
    public decimal? R11_T11 { get; set; }
    public decimal? R11_T12 { get; set; }
    public decimal? R11_T13 { get; set; }
    public decimal? R11_T14 { get; set; }
    public decimal? R11_T15 { get; set; }
    public decimal? R11_T16 { get; set; }
    public decimal? R11_VIN { get; set; }
    public decimal? R11_IIN { get; set; }
    public decimal? R11_PIN { get; set; }
    public decimal? R11_TJ { get; set; }
    public decimal? R12_TimeHrs { get; set; }
    public decimal? R12_T1 { get; set; }
    public decimal? R12_T2 { get; set; }
    public decimal? R12_T3 { get; set; }
    public decimal? R12_T4 { get; set; }
    public decimal? R12_T5 { get; set; }
    public decimal? R12_T6 { get; set; }
    public decimal? R12_T7 { get; set; }
    public decimal? R12_T8 { get; set; }
    public decimal? R12_T9 { get; set; }
    public decimal? R12_T10 { get; set; }
    public decimal? R12_T11 { get; set; }
    public decimal? R12_T12 { get; set; }
    public decimal? R12_T13 { get; set; }
    public decimal? R12_T14 { get; set; }
    public decimal? R12_T15 { get; set; }
    public decimal? R12_T16 { get; set; }
    public decimal? R12_VIN { get; set; }
    public decimal? R12_IIN { get; set; }
    public decimal? R12_PIN { get; set; }
    public decimal? R12_TJ { get; set; }
    public decimal? MaxVal_T1 { get; set; }
    public decimal? MaxVal_T2 { get; set; }
    public decimal? MaxVal_T3 { get; set; }
    public decimal? MaxVal_T4 { get; set; }
    public decimal? MaxVal_T5 { get; set; }
    public decimal? MaxVal_T6 { get; set; }
    public decimal? MaxVal_T7 { get; set; }
    public decimal? MaxVal_T8 { get; set; }
    public decimal? MaxVal_T9 { get; set; }
    public decimal? MaxVal_T10 { get; set; }
    public decimal? MaxVal_T11 { get; set; }
    public decimal? MaxVal_T12 { get; set; }
    public decimal? MaxVal_T13 { get; set; }
    public decimal? MaxVal_T14 { get; set; }
    public decimal? MaxVal_T15 { get; set; }
    public decimal? MaxVal_T16 { get; set; }
    public decimal? MaxVal_TJ { get; set; }
    public decimal? Conclusion_MaxRecordedTJ { get; set; }
    public decimal? Conclusion_AllowableTJ { get; set; }
    public decimal? Conclusion_MaxRecordedDriverTc { get; set; }
    public decimal? Conclusion_AllowableDriverTc { get; set; }
    public decimal? Conclusion_MaxRecordedLensTemp { get; set; }
    public string? Conclusion_OverThermalCutoff { get; set; }
    public string? Conclusion_Result { get; set; }
    public string? ConductedBy { get; set; }
    public string? WitnessBy { get; set; }
    public string? ApprovedBy { get; set; }
    public int AddedBy { get; set; }
    public DateTime AddedOn { get; set; }
    public int? UpdatedBy { get; set; }
    public DateTime? UpdatedOn { get; set; }
    public string? User { get; set; }
}
