using QMS.Core.DatabaseContext.Shared;
using System.ComponentModel.DataAnnotations.Schema;

namespace QMS.Core.DatabaseContext;

[Table("tbl_ElectricalPerformance")]
public class ElectricalPerformance : SqlTable
{
    public string? ProductCatRef { get; set; }
    public string? ProductDescription { get; set; }
    public string? ReportNo { get; set; }
    public string? LightSourceDetails { get; set; }
    public string? DriverDetails { get; set; }
    public DateTime? ReportDate { get; set; }
    public string? PCBDetails { get; set; }
    public string? LEDCombinations { get; set; }
    public string? BatchCode { get; set; }
    public string? SensorDetails { get; set; }
    public string? LampDetails { get; set; }
    public string? PKD { get; set; }
    public string? S1_BS_Vac { get; set; }
    public string? S1_BS_IacA { get; set; }
    public string? S1_BS_Wac { get; set; }
    public string? S1_BS_PF { get; set; }
    public string? S1_BS_ATHD { get; set; }
    public string? S1_BS_Vdc { get; set; }
    public string? S1_BS_IdcA { get; set; }
    public string? S1_BS_Wdc { get; set; }
    public string? S1_BS_Eff { get; set; }
    public string? S1_BS_NoLoadV { get; set; }
    public string? S1_BS_StartV { get; set; }
    public string? S1_BS_Result { get; set; }
    public string? S1_AS_Vac { get; set; }
    public string? S1_AS_IacA { get; set; }
    public string? S1_AS_Wac { get; set; }
    public string? S1_AS_PF { get; set; }
    public string? S1_AS_ATHD { get; set; }
    public string? S1_AS_Vdc { get; set; }
    public string? S1_AS_IdcA { get; set; }
    public string? S1_AS_Wdc { get; set; }
    public string? S1_AS_Eff { get; set; }
    public string? S1_AS_NoLoadV { get; set; }
    public string? S1_AS_StartV { get; set; }
    public string? S1_AS_Result { get; set; }
    public string? S2_BS_Vac { get; set; }
    public string? S2_BS_IacA { get; set; }
    public string? S2_BS_Wac { get; set; }
    public string? S2_BS_PF { get; set; }
    public string? S2_BS_ATHD { get; set; }
    public string? S2_BS_Vdc { get; set; }
    public string? S2_BS_IdcA { get; set; }
    public string? S2_BS_Wdc { get; set; }
    public string? S2_BS_Eff { get; set; }
    public string? S2_BS_NoLoadV { get; set; }
    public string? S2_BS_StartV { get; set; }
    public string? S2_BS_Result { get; set; }
    public string? S2_AS_Vac { get; set; }
    public string? S2_AS_IacA { get; set; }
    public string? S2_AS_Wac { get; set; }
    public string? S2_AS_PF { get; set; }
    public string? S2_AS_ATHD { get; set; }
    public string? S2_AS_Vdc { get; set; }
    public string? S2_AS_IdcA { get; set; }
    public string? S2_AS_Wdc { get; set; }
    public string? S2_AS_Eff { get; set; }
    public string? S2_AS_NoLoadV { get; set; }
    public string? S2_AS_StartV { get; set; }
    public string? S2_AS_Result { get; set; }
    public string? S3_BS_Vac { get; set; }
    public string? S3_BS_IacA { get; set; }
    public string? S3_BS_Wac { get; set; }
    public string? S3_BS_PF { get; set; }
    public string? S3_BS_ATHD { get; set; }
    public string? S3_BS_Vdc { get; set; }
    public string? S3_BS_IdcA { get; set; }
    public string? S3_BS_Wdc { get; set; }
    public string? S3_BS_Eff { get; set; }
    public string? S3_BS_NoLoadV { get; set; }
    public string? S3_BS_StartV { get; set; }
    public string? S3_BS_Result { get; set; }
    public string? S3_AS_Vac { get; set; }
    public string? S3_AS_IacA { get; set; }
    public string? S3_AS_Wac { get; set; }
    public string? S3_AS_PF { get; set; }
    public string? S3_AS_ATHD { get; set; }
    public string? S3_AS_Vdc { get; set; }
    public string? S3_AS_IdcA { get; set; }
    public string? S3_AS_Wdc { get; set; }
    public string? S3_AS_Eff { get; set; }
    public string? S3_AS_NoLoadV { get; set; }
    public string? S3_AS_StartV { get; set; }
    public string? S3_AS_Result { get; set; }
    public string? S4_BS_Vac { get; set; }
    public string? S4_BS_IacA { get; set; }
    public string? S4_BS_Wac { get; set; }
    public string? S4_BS_PF { get; set; }
    public string? S4_BS_ATHD { get; set; }
    public string? S4_BS_Vdc { get; set; }
    public string? S4_BS_IdcA { get; set; }
    public string? S4_BS_Wdc { get; set; }
    public string? S4_BS_Eff { get; set; }
    public string? S4_BS_NoLoadV { get; set; }
    public string? S4_BS_StartV { get; set; }
    public string? S4_BS_Result { get; set; }
    public string? S4_AS_Vac { get; set; }
    public string? S4_AS_IacA { get; set; }
    public string? S4_AS_Wac { get; set; }
    public string? S4_AS_PF { get; set; }
    public string? S4_AS_ATHD { get; set; }
    public string? S4_AS_Vdc { get; set; }
    public string? S4_AS_IdcA { get; set; }
    public string? S4_AS_Wdc { get; set; }
    public string? S4_AS_Eff { get; set; }
    public string? S4_AS_NoLoadV { get; set; }
    public string? S4_AS_StartV { get; set; }
    public string? S4_AS_Result { get; set; }
    public string? S5_BS_Vac { get; set; }
    public string? S5_BS_IacA { get; set; }
    public string? S5_BS_Wac { get; set; }
    public string? S5_BS_PF { get; set; }
    public string? S5_BS_ATHD { get; set; }
    public string? S5_BS_Vdc { get; set; }
    public string? S5_BS_IdcA { get; set; }
    public string? S5_BS_Wdc { get; set; }
    public string? S5_BS_Eff { get; set; }
    public string? S5_BS_NoLoadV { get; set; }
    public string? S5_BS_StartV { get; set; }
    public string? S5_BS_Result { get; set; }
    public string? S5_AS_Vac { get; set; }
    public string? S5_AS_IacA { get; set; }
    public string? S5_AS_Wac { get; set; }
    public string? S5_AS_PF { get; set; }
    public string? S5_AS_ATHD { get; set; }
    public string? S5_AS_Vdc { get; set; }
    public string? S5_AS_IdcA { get; set; }
    public string? S5_AS_Wdc { get; set; }
    public string? S5_AS_Eff { get; set; }
    public string? S5_AS_NoLoadV { get; set; }
    public string? S5_AS_StartV { get; set; }
    public string? S5_AS_Result { get; set; }
    public string? OverallResult { get; set; }
    public string? TestedByName { get; set; }
    public string? VerifiedByName { get; set; }
    public int AddedBy { get; set; }
    public DateTime AddedOn { get; set; }
    public int? UpdatedBy { get; set; }
    public DateTime? UpdatedOn { get; set; }
}
