using QMS.Core.DatabaseContext.Shared;
using System.ComponentModel.DataAnnotations.Schema;

namespace QMS.Core.DatabaseContext;

[Table("tbl_ElectricalProtection")]
public class ElectricalProtection : SqlTable
{
    public string? ProductCatRef { get; set; }
    public string? ProductDescription { get; set; }
    public string? ReportNo { get; set; }
    public DateTime? ReportDate { get; set; }
    public string? BatchCode { get; set; }
    public string? PKD { get; set; }
    public string? LightSourceDetails { get; set; }
    public string? DriverDetailsQty { get; set; }
    public string? PCBDetailsQty { get; set; }
    public string? LEDCombinations { get; set; }
    public string? SensorDetailsQty { get; set; }
    public string? LampDetails { get; set; }
    public string? UnderVoltage_Sample1 { get; set; }
    public string? UnderVoltage_Sample2 { get; set; }
    public string? UnderVoltage_Sample3 { get; set; }
    public string? UnderVoltage_Sample4 { get; set; }
    public string? UnderVoltage_Sample5 { get; set; }
    public string? UnderVoltage_Result { get; set; }
    public string? OverVoltage_Sample1 { get; set; }
    public string? OverVoltage_Sample2 { get; set; }
    public string? OverVoltage_Sample3 { get; set; }
    public string? OverVoltage_Sample4 { get; set; }
    public string? OverVoltage_Sample5 { get; set; }
    public string? OverVoltage_Result { get; set; }
    public string? OpenCircuit_Sample1 { get; set; }
    public string? OpenCircuit_Sample2 { get; set; }
    public string? OpenCircuit_Sample3 { get; set; }
    public string? OpenCircuit_Sample4 { get; set; }
    public string? OpenCircuit_Sample5 { get; set; }
    public string? OpenCircuit_Result { get; set; }
    public string? ShortCircuit_Sample1 { get; set; }
    public string? ShortCircuit_Sample2 { get; set; }
    public string? ShortCircuit_Sample3 { get; set; }
    public string? ShortCircuit_Sample4 { get; set; }
    public string? ShortCircuit_Sample5 { get; set; }
    public string? ShortCircuit_Result { get; set; }
    public string? ReversePolarity_Sample1 { get; set; }
    public string? ReversePolarity_Sample2 { get; set; }
    public string? ReversePolarity_Sample3 { get; set; }
    public string? ReversePolarity_Sample4 { get; set; }
    public string? ReversePolarity_Sample5 { get; set; }
    public string? ReversePolarity_Result { get; set; }
    public string? OverLoad_Sample1 { get; set; }
    public string? OverLoad_Sample2 { get; set; }
    public string? OverLoad_Sample3 { get; set; }
    public string? OverLoad_Sample4 { get; set; }
    public string? OverLoad_Sample5 { get; set; }
    public string? OverLoad_Result { get; set; }
    public string? OverThermal_Sample1 { get; set; }
    public string? OverThermal_Sample2 { get; set; }
    public string? OverThermal_Sample3 { get; set; }
    public string? OverThermal_Sample4 { get; set; }
    public string? OverThermal_Sample5 { get; set; }
    public string? OverThermal_Result { get; set; }
    public string? EarthFault_Sample1 { get; set; }
    public string? EarthFault_Sample2 { get; set; }
    public string? EarthFault_Sample3 { get; set; }
    public string? EarthFault_Sample4 { get; set; }
    public string? EarthFault_Sample5 { get; set; }
    public string? EarthFault_Result { get; set; }
    public string? DriverIsolation_Sample1 { get; set; }
    public string? DriverIsolation_Sample2 { get; set; }
    public string? DriverIsolation_Sample3 { get; set; }
    public string? DriverIsolation_Sample4 { get; set; }
    public string? DriverIsolation_Sample5 { get; set; }
    public string? DriverIsolation_Result { get; set; }
    public string? HighVoltage_Sample1 { get; set; }
    public string? HighVoltage_Sample2 { get; set; }
    public string? HighVoltage_Sample3 { get; set; }
    public string? HighVoltage_Sample4 { get; set; }
    public string? HighVoltage_Sample5 { get; set; }
    public string? HighVoltage_Result { get; set; }
    public string? HV_Sample1 { get; set; }
    public string? HV_Sample2 { get; set; }
    public string? HV_Sample3 { get; set; }
    public string? HV_Sample4 { get; set; }
    public string? HV_Sample5 { get; set; }
    public string? HV_Result { get; set; }
    public string? InsulationResistance_Sample1 { get; set; }
    public string? InsulationResistance_Sample2 { get; set; }
    public string? InsulationResistance_Sample3 { get; set; }
    public string? InsulationResistance_Sample4 { get; set; }
    public string? InsulationResistance_Sample5 { get; set; }
    public string? InsulationResistance_Result { get; set; }
    public string? EarthContinuity_Sample1 { get; set; }
    public string? EarthContinuity_Sample2 { get; set; }
    public string? EarthContinuity_Sample3 { get; set; }
    public string? EarthContinuity_Sample4 { get; set; }
    public string? EarthContinuity_Sample5 { get; set; }
    public string? EarthContinuity_Result { get; set; }
    public string? SELVProtection_Sample1 { get; set; }
    public string? SELVProtection_Sample2 { get; set; }
    public string? SELVProtection_Sample3 { get; set; }
    public string? SELVProtection_Sample4 { get; set; }
    public string? SELVProtection_Sample5 { get; set; }
    public string? SELVProtection_Result { get; set; }
    public string? LeakageCurrent_Sample1 { get; set; }
    public string? LeakageCurrent_Sample2 { get; set; }
    public string? LeakageCurrent_Sample3 { get; set; }
    public string? LeakageCurrent_Sample4 { get; set; }
    public string? LeakageCurrent_Sample5 { get; set; }
    public string? LeakageCurrent_Result { get; set; }
    public string? CreepageClearance_Sample1 { get; set; }
    public string? CreepageClearance_Sample2 { get; set; }
    public string? CreepageClearance_Sample3 { get; set; }
    public string? CreepageClearance_Sample4 { get; set; }
    public string? CreepageClearance_Sample5 { get; set; }
    public string? CreepageClearance_Result { get; set; }
    public string? HiPotMCPCB_Sample1 { get; set; }
    public string? HiPotMCPCB_Sample2 { get; set; }
    public string? HiPotMCPCB_Sample3 { get; set; }
    public string? HiPotMCPCB_Sample4 { get; set; }
    public string? HiPotMCPCB_Sample5 { get; set; }
    public string? HiPotMCPCB_Result { get; set; }
    public string? OnOffSwitching_Sample1 { get; set; }
    public string? OnOffSwitching_Sample2 { get; set; }
    public string? OnOffSwitching_Sample3 { get; set; }
    public string? OnOffSwitching_Sample4 { get; set; }
    public string? OnOffSwitching_Sample5 { get; set; }
    public string? OnOffSwitching_Result { get; set; }
    public string? SoakingAgeing_Sample1 { get; set; }
    public string? SoakingAgeing_Sample2 { get; set; }
    public string? SoakingAgeing_Sample3 { get; set; }
    public string? SoakingAgeing_Sample4 { get; set; }
    public string? SoakingAgeing_Sample5 { get; set; }
    public string? SoakingAgeing_Result { get; set; }
    public string? RollingEndurance_Sample1 { get; set; }
    public string? RollingEndurance_Sample2 { get; set; }
    public string? RollingEndurance_Sample3 { get; set; }
    public string? RollingEndurance_Sample4 { get; set; }
    public string? RollingEndurance_Sample5 { get; set; }
    public string? RollingEndurance_Result { get; set; }
    public string? GlowTest_Sample1 { get; set; }
    public string? GlowTest_Sample2 { get; set; }
    public string? GlowTest_Sample3 { get; set; }
    public string? GlowTest_Sample4 { get; set; }
    public string? GlowTest_Sample5 { get; set; }
    public string? GlowTest_Result { get; set; }
    public string? LampAccommodation_Sample1 { get; set; }
    public string? LampAccommodation_Sample2 { get; set; }
    public string? LampAccommodation_Sample3 { get; set; }
    public string? LampAccommodation_Sample4 { get; set; }
    public string? LampAccommodation_Sample5 { get; set; }
    public string? LampAccommodation_Result { get; set; }
    public string? DaliFunction_Sample1 { get; set; }
    public string? DaliFunction_Sample2 { get; set; }
    public string? DaliFunction_Sample3 { get; set; }
    public string? DaliFunction_Sample4 { get; set; }
    public string? DaliFunction_Sample5 { get; set; }
    public string? DaliFunction_Result { get; set; }
    public string? TuneableCCT_Sample1 { get; set; }
    public string? TuneableCCT_Sample2 { get; set; }
    public string? TuneableCCT_Sample3 { get; set; }
    public string? TuneableCCT_Sample4 { get; set; }
    public string? TuneableCCT_Sample5 { get; set; }
    public string? TuneableCCT_Result { get; set; }
    public string? BatteryBackup_Sample1 { get; set; }
    public string? BatteryBackup_Sample2 { get; set; }
    public string? BatteryBackup_Sample3 { get; set; }
    public string? BatteryBackup_Sample4 { get; set; }
    public string? BatteryBackup_Sample5 { get; set; }
    public string? BatteryBackup_Result { get; set; }
    public string? SmartLighting_Sample1 { get; set; }
    public string? SmartLighting_Sample2 { get; set; }
    public string? SmartLighting_Sample3 { get; set; }
    public string? SmartLighting_Sample4 { get; set; }
    public string? SmartLighting_Sample5 { get; set; }
    public string? SmartLighting_Result { get; set; }
    public string? SensorFunction_Sample1 { get; set; }
    public string? SensorFunction_Sample2 { get; set; }
    public string? SensorFunction_Sample3 { get; set; }
    public string? SensorFunction_Sample4 { get; set; }
    public string? SensorFunction_Sample5 { get; set; }
    public string? SensorFunction_Result { get; set; }
    public string? OverallReportResult { get; set; }
    public string? TestedByName { get; set; }
    public string? VerifiedByName { get; set; }
    public int AddedBy { get; set; }
    public DateTime AddedOn { get; set; }
    public int? UpdatedBy { get; set; }
    public DateTime? UpdatedOn { get; set; }
}
